filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

output.logstash:
  hosts: 'logstash:5044'

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:elastic}'
#   password: '${ELASTICSEARCH_PASSWORD:changeme}'

# setup.kibana:
#   host: 'kibana:5601'

# filebeat.modules:
#   - module: system
