apm-server:
  host: "localhost:8200"
  rum:
    enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  enabled: true
  username: "elastic"
  password: "changeme"

queue.mem.events: 4096

max_procs: 4

tls.selfSignedCertificate.disabled: true
