---
version: '3.9'
x-elasticsearch: &elasticsearch_config
  image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  ulimits:
    memlock:
      hard: -1
      soft: -1
  networks:
    - elastic
services:
  elasticsearch:
    <<: *elasticsearch_config
    container_name: elasticsearch
    environment:
      - "NODE_NAME=elasticsearch"
      - "INITIAL_MASTER_NODES=elasticsearch,elasticsearch_2,elasticsearch_3"
      - "SEED_HOSTS=elasticsearch_2,elasticsearch_3"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  elasticsearch_2:
    <<: *elasticsearch_config
    container_name: elasticsearch_2
    environment:
      - "NODE_NAME=elasticsearch_2"
      - "INITIAL_MASTER_NODES=elasticsearch,elasticsearch_2,elasticsearch_3"
      - "SEED_HOSTS=elasticsearch,elasticsearch_3"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_2:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  elasticsearch_3:
    <<: *elasticsearch_config
    container_name: elasticsearch_3
    environment:
      - "NODE_NAME=elasticsearch_3"
      - "INITIAL_MASTER_NODES=elasticsearch,elasticsearch_2,elasticsearch_3"
      - "SEED_HOSTS=elasticsearch,elasticsearch_2"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_3:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./logstash/pipelines:/usr/share/logstash/pipeline
      - ./logstash/settings/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    command: logstash
    networks:
      - elastic
    ports:
      - 5000:5000 # syslog system port
      - 5044:5044 # default beats port
      - 9600:9600 # node web api port

  # apm:
  #   image: docker.elastic.co/apm/apm-server:7.10.0
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #     kibana:
  #       condition: service_healthy
  #   cap_add: ['CHOWN', 'DAC_OVERRIDE', 'SETGID', 'SETUID']
  #   cap_drop: ['ALL']
  #   ports:
  #     - 8200:8200
  #   networks:
  #     - elastic
  #   command: >
  #     apm-server -e
  #       -E setup.kibana.host=kibana:5601
  #   volumes:
  #     - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   healthcheck:
  #     interval: 10s
  #     retries: 12
  #     test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elastic

  # metricbeat:
  #   image: docker.elastic.co/beats/metricbeat:7.10.0
  #   networks:
  #     - elastic
    # environment:
    #   - ELASTICSEARCH_HOST=http://elasticsearch:9200
    #   - KIBANA_HOST=http://kibana:5601
    #   - ELASTICSEARCH_USERNAME=elastic
    #   - ELASTICSEARCH_PASSWORD=changeme
networks:
  elastic:
    driver: bridge
volumes:
  elasticsearch_data:
  elasticsearch_data_2:
  elasticsearch_data_3:
