---
version: '3.9'
x-elasticsearch: &elasticsearch_config
  image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  ulimits:
    memlock:
      hard: -1
      soft: -1
  networks:
    - elastic
services:
  elasticsearch:
    <<: *elasticsearch_config
    container_name: elasticsearch
    environment:
      - "NODE_NAME=elasticsearch"
      # - "INITIAL_MASTER_NODES=elasticsearch,elasticsearch_2,elasticsearch_3"
      # - "SEED_HOSTS=elasticsearch_2,elasticsearch_3"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - APM_SYSTEM_PASSWORD=${APM_SYSTEM_PASSWORD}
      # - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      # - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      # - LOGSTASH_SYSTEM_PASSWORD=${LOGSTASH_SYSTEM_PASSWORD}
      # - BEATS_SYSTEM_PASSWORD=${BEATS_SYSTEM_PASSWORD}
      # - REMOTE_MONITORING_USER_PASSWORD=${REMOTE_MONITORING_USER_PASSWORD}
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  elasticsearch_2:
    <<: *elasticsearch_config
    container_name: elasticsearch_2
    environment:
      - "NODE_NAME=elasticsearch_2"
      - "INITIAL_MASTER_NODES=elasticsearch,elasticsearch_2,elasticsearch_3"
      - "SEED_HOSTS=elasticsearch,elasticsearch_3"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_2:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  elasticsearch_3:
    <<: *elasticsearch_config
    container_name: elasticsearch_3
    environment:
      - "NODE_NAME=elasticsearch_3"
      - "INITIAL_MASTER_NODES=elasticsearch,elasticsearch_2,elasticsearch_3"
      - "SEED_HOSTS=elasticsearch,elasticsearch_2"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_3:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    hostname: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./logstash/pipelines:/usr/share/logstash/pipeline
      - ./logstash/settings/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    command: logstash
    networks:
      - elastic
    ports:
      - 5000:5000 # syslog system port
      - 5044:5044 # default beats port
      - 9600:9600 # node web api port

  apm:
    image: docker.elastic.co/apm/apm-server:7.10.0
    container_name: apm
    hostname: apm
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ['CHOWN', 'DAC_OVERRIDE', 'SETGID', 'SETUID']
    cap_drop: ['ALL']
    ports:
      - 8200:8200
    networks:
      - elastic
    volumes:
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - filebeat_data:/usr/share/filebeat/data/
    networks:
      - elastic

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.10.0
    container_name: metricbeat
    hostname: metricbeat
    # user: root
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /:/hostfs:ro
    networks:
      - elastic

  # bootstrap:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  #   container_name: bootstrap
  #   hostname: bootstrap
  #   environment:
  #     - APM_SYSTEM_PASSWORD=${APM_SYSTEM_PASSWORD}
  #     - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
  #     - KIBANA_PASSWORD=${KIBANA_PASSWORD}
  #     - LOGSTASH_SYSTEM_PASSWORD=${LOGSTASH_SYSTEM_PASSWORD}
  #     - BEATS_SYSTEM_PASSWORD=${BEATS_SYSTEM_PASSWORD}
  #     - REMOTE_MONITORING_USER_PASSWORD=${REMOTE_MONITORING_USER_PASSWORD}
  #     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   volumes:
  #     - ./bootstrap.sh:/usr/local/bin/bootstrap.sh:ro
  #   command: ['/bin/bash', '-c', '/usr/local/bin/bootstrap.sh']
  #   networks:
  #     - elastic

networks:
  elastic:
    driver: bridge
volumes:
  elasticsearch_data:
  elasticsearch_data_2:
  elasticsearch_data_3:
  filebeat_data:
