---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-0
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/elasticsearch/data/nodes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-1
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/elasticsearch/data/nodes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-2
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/elasticsearch/data/nodes
