---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-master-elasticsearch-master-0
  namespace: elastic
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-master-elasticsearch-master-1
  namespace: elastic
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-master-elasticsearch-master-2
  namespace: elastic
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
