---
image: docker.elastic.co/logstash/logstash
imageTag: "7.9.3"
imagePullPolicy: "IfNotPresent"

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
    output { elasticsearch { hosts => ["http://elasticsearch-master:9200"] index => "logstash" } }

logstashJavaOpts: "-Xmx128m -Xms128m"

resources:
  requests:
    cpu: "250m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"
persistence:
  enabled: true

volumeClaimTemplate:
  storageClassName: hostpath
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostpath
