---
image: docker.elastic.co/kibana/kibana
imageTag: "7.9.3"
imagePullPolicy: "IfNotPresent"

elasticsearchHosts: "http://elasticsearch-master:9200"

replicas: 1
# Required for healthcheck
protocol: http
httpPort: 5601

service:
  type: NodePort
  port: 5601
  httpPortName: http

resources:
  requests:
    cpu: "750m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
